@echo off
echo Pulling latest code from Git...
git pull
echo Setting up Python Virtual Environment...
if not exist venv (
    python -m venv venv
)
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Salesforce Metadata Deployer...
uvicorn app:app --reload --port 8000
